setwd("/Users/ChatNoir/Projects/Squam/RevBayes/Amp_Results/ampOut")

BRL1Ptab <- read.table("amp.pVal.tab", header=TRUE, sep="")
x = c(seq(0,1,0.02))

pdf(file='999th-1000q.pdf')
#parses graphing space into 3 rows and 1 column
par(mfrow=c(3,1))
hist(BRL1Ptab[,2], col="grey", main="9999th 10000-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,3], col="grey", main="9999th 10000-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,4], col="grey", main="9999th 10000-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='99th-100q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,5], col="grey", main="999th 1000-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,6], col="grey", main="999th 1000-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,7], col="grey", main="999th 1000-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='3th-4q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,8], col="grey", main="99th 100-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,9], col="grey", main="99th 100-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,10], col="grey", main="99th 100-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='2th-4q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,11], col="grey", main="3rd 4-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,12], col="grey", main="3rd 4-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,13], col="grey", main="3rd 4-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-4q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,14], col="grey", main="2nd 4-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,15], col="grey", main="2nd 4-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,16], col="grey", main="2nd 4-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-6q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,17], col="grey", main="1st 4-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,18], col="grey", main="1st 4-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,19], col="grey", main="1st 4-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-8q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,20], col="grey", main="1st 6-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,21], col="grey", main="1st 6-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,22], col="grey", main="1st 6-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-10q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,23], col="grey", main="1st 8-quantile Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,24], col="grey", main="1st 8-quantile Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,25], col="grey", main="1st 8-quantile Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-20q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,26], col="grey", main="Mean Tree Length Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,27], col="grey", main="Mean Tree Length Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,28], col="grey", main="Mean Tree Length Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-100q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,29], col="grey", main="Tree Length Variance Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,30], col="grey", main="Tree Length Variance Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,31], col="grey", main="Tree Length Variance Two-tail", xlab="P-values", breaks=x)
dev.off()

pdf(file='1th-1000q.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,32], col="grey", main="1st 100-quantile Lower-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,33], col="grey", main="1st 100-quantile Upper-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,34], col="grey", main="1st 100-quantile Two-tail", xlab="P-values", breaks=5)
dev.off()

pdf(file='IQR.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,35], col="grey", main="1st 1000-quantile Lower-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,36], col="grey", main="1st 1000-quantile Upper-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,37], col="grey", main="1st 1000-quantile Two-tail", xlab="P-values", breaks=5)
dev.off()

pdf(file='MeanTreeLength.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,38], col="grey", main="Interquartile Range Lower-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,39], col="grey", main="Interquartile Range Upper-tail", xlab="P-values", breaks=5)
hist(BRL1Ptab[,40], col="grey", main="Interquartile Range Two-tail", xlab="P-values", breaks=5)
dev.off()

pdf(file='TreeLengthVariance.pdf')
par(mfrow=c(3,1))
hist(BRL1Ptab[,41], col="grey", main="Mean Tree Length Lower-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,42], col="grey", main="Mean Tree Length Upper-tail", xlab="P-values", breaks=x)
hist(BRL1Ptab[,43], col="grey", main="Mean Tree Length Two-tail", xlab="P-values", breaks=x)
dev.off()



